project:
  type: website
  output-dir: docs

website:
  title: "SDS290- Spring 2025"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: https://docs.google.com/spreadsheets/d/131eOI-EH2uypTRMhCbW6aT2lEGNJbUA2T7GS2MAHOOA/edit?usp=sharing
        text: Course Schedule
      - text: Mini Projects
        menu:
        - href: mp_1.qmd
          text: Mini Project 1
        - href: mp_2.qmd
          text: Mini Project 2
      - href: homework.qmd
        text: Homework
      - text: Trouble shooting links
        menu:
        - href: https://smithcollege-sds.github.io/sds100/lab_01_setup.html
          text: Downloading R and RStudio
        - text: Basics of Data Wranging in R
          href: https://smithcollege-sds.github.io/sds100/lab_04_wrangling.html
        - text: Troubleshooting R Markdown
          href: https://smithcollege-sds.github.io/sds-www/rmarkdown_problems.html
        - text: Qualtrics
          href: https://smithcollege.qualtrics.com/
      - text: Lecture Slides
        menu:
        - href: https://docs.google.com/presentation/d/1_R8oM8LSbJyaFBlIEGB31M1k7TqpZnCq/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Intro Slides
        - href: https://docs.google.com/presentation/d/1iuOF-yE--y02bcfquKVXsB_uE-oy4p13/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 2- Introduction to Anova
        - href: https://docs.google.com/presentation/d/1l1KE-jbf2R31j1K4IBb2HK7RXkBATnJ1/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 3- Anova Conditions
        - href: https://docs.google.com/presentation/d/1oPj9zoOtSRFNw_rf7SfNs1nvxCEzPbpi/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 4- Confidence Intervals, Effect Size, and Transformation
        - href: https://docs.google.com/presentation/d/1tYDcveFa7dvm0LJmbKvRf5I6D2xiMHIZ/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 5- One Way Anova Continued 
        - href: https://docs.google.com/presentation/d/1z3o-3UGxc5ONbAr7ceyk58mNcMRr2ul4/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 7- Two-way Anova
        - href: https://docs.google.com/presentation/d/10nz6uuZPpQIO9Mi49AiN-QdxicXrOI9z/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 8- Interactions
        - href: https://docs.google.com/presentation/d/17A-kWRz8zl9V8fTm_Cx36tqFHoffh5Py/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 9- Interactions Part 2
        - href: https://docs.google.com/presentation/d/19FHEe-eb57QA2fJgi2BkRWhp6VoHStNs/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 10- Selected Topics 1
        - href: https://docs.google.com/presentation/d/1C2g7P8Vkrhl6b82mDVrrGil2rcAD3z4H/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 11- Selected Topics 2
      - text: Sample Code
        href: sample_code.qmd
  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

