project:
  type: website
  output-dir: docs

website:
  title: "SDS290- Spring 2025"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: https://docs.google.com/spreadsheets/d/131eOI-EH2uypTRMhCbW6aT2lEGNJbUA2T7GS2MAHOOA/edit?usp=sharing
        text: Course Schedule
      - text: Mini Projects
        menu:
        - href: mp_1.qmd
          text: Mini Project 1
        - href: mp_2.qmd
          text: Mini Project 2
      - href: homework.qmd
        text: Homework
      - text: Trouble shooting links
        menu:
        - href: https://smithcollege-sds.github.io/sds100/lab_01_setup.html
          text: Downloading R and RStudio
        - text: Basics of Data Wranging in R
          href: https://smithcollege-sds.github.io/sds100/lab_04_wrangling.html
        - text: Troubleshooting R Markdown
          href: https://smithcollege-sds.github.io/sds-www/rmarkdown_problems.html
        - text: Qualtrics
          href: https://smithcollege.qualtrics.com/
      - text: Lecture Slides
        menu:
        - href: https://docs.google.com/presentation/d/1_R8oM8LSbJyaFBlIEGB31M1k7TqpZnCq/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Intro Slides
        - href: https://docs.google.com/presentation/d/1iuOF-yE--y02bcfquKVXsB_uE-oy4p13/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 2- Introduction to Anova

      - text: Sample Code
        href: sample_code.qmd
  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

