project:
  type: website

website:
  title: "SDS290 Spring 2025"

format:
  html:
    theme: cosmo
    css: styles.css

# Optional: Include a navigation menu if needed
navbar:
  left:
    - text: "Home"
      href: index.qmd
    - text: "Syllabus"
      href: syllabus.qmd
    - text: "Introduction"
      href: introduction.qmd
